[build]
target = "riscv32i-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Map=target/memory.map",
  "-C", "link-arg=--gc-sections",
  "-C", "linker=rust-lld",
  "-C", "default-linker-libraries=no"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv32i-unknown-none-elf]
runner = "qemu-system-riscv32 -machine sifive_e -nographic -kernel"
